name: 'Test'
author: 'Penelope Yong'
description: 'Test'

inputs:
  paths:
    description: 'paths'
    required: false
    default: ''


runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Julia
      uses: julia-actions/setup-julia@v2

    - name: Install docs dependencies
      shell: julia --color=yes {0}
      env:
        PATHS: ${{ inputs.paths }}
      run: |
        using Pkg
        pkg_path = ENV["PATHS"]
        for path in split(pkg_path, "\n")
            path = strip(path)
            if path != ""
                println("Got path: $path")
            end
        end
