name: ch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    runs-on: ubuntu-latest

    steps:
      - name: Run (my fork of) CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add(url="https://github.com/penelopeysm/CompatHelper.jl", rev="main")
          using CompatHelper
          CompatHelper.main()
