name: ch

on:
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest

    steps:
      - name: Add my CompatHelper fork
        run: julia -e 'using Pkg; Pkg.add(url="https://github.com/penelopeysm/CompatHelper.jl", rev="main")'

      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
