on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: exit 1

      - name: Echo
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        run: echo "Hello, world!"
