on:
  push:
    branches: [main]

jobs:
  build-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Cache Julia dependencies
        uses: julia-actions/cache@v2

      - name: Instantiate docs project
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build docs
        run: julia --project=docs/ --color=yes docs/make.jl

      - name: Insert navigation bar
        uses: shravanngoswamii/DocsNav@py/locally

      - name: Deploy docs
        run: julia --project=docs/ --color=yes -e 'using Documenter; deploydocs(; repo="github.com/penelopeysm/Shaymin.jl.git", push_preview=true)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
