on:
  push:
    branches: [main]

jobs:
  build-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Build Documenter.jl docs
        uses: TuringLang/DocsNav/DocsDocumenter@py/multiple-actions
