on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: exit 1
        continue-on-error: true

      - name: Echo
        run: echo "Hello, world!"
