name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia-version: ['1.10', '1.11', '1.12', 'pre']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - uses: julia-actions/cache@v3

      - name: Instantiate
        working-directory: .github/workflows
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run script
        working-directory: .github/workflows
        run: julia --project=. wishartenzyme.jl
